version: '3.8'

services:
  # FastAPI 백엔드 서비스
  backend:
    build: .
    container_name: real_estate_backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./real_estate_hub.db:/app/real_estate_hub.db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URI=sqlite:///./real_estate_hub.db
    depends_on:
      - redis
    networks:
      - real_estate_network
    restart: unless-stopped

  # Redis 서비스 (캐싱 및 세션 관리용)
  redis:
    image: redis:7-alpine
    container_name: real_estate_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - real_estate_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: real_estate_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
    depends_on:
      - backend
    networks:
      - real_estate_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  real_estate_network:
    driver: bridge
